version: '3'
services:
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: healthcare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Apple@1234
      TZ: 'Asia/Tokyo'

networks:
  db:
    driver: bridge